### ISSUE TITLE
Validate script error

### ISSUE THREAD

**Issue by QuantumInformation** [blinfo/angular2-webpack-seed#2]
When running `npm run validate` I get this:

PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  Error: Missing: SyncTestZoneSpec
  at webpack:///~/zone.js/dist/jasmine-patch.js:66:0 <- config/karma-test-shim.js:60551

**Comment by jorawarsingh** [comment]
if you have upgraded zone to latest version that can cause this issue. down grading to `"zone.js": "^0.6.13"` should resolve this.

**Comment by kevalwell** [comment]
@jorawarsingh This did not fix the issue for me.

**Comment by jorawarsingh** [comment]
@Kevalwell have you checked out the latest code from seed?
