### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by 799956381** [blinfo/angular2-webpack-seed#4]
Issues with npm run build error
> ERROR in chunk app [initial]
[name].[hash].js
Template cannot be applied as TemplateArgument: HarmonyImportDependency

19 verbose pkgid angular2webpack-seed@1.0.0
20 verbose cwd F:\Github\angular2-webpack-seed
21 error Windows_NT 6.1.7601
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
23 error node v4.5.0
24 error npm  v3.10.7
25 error code ELIFECYCLE
26 error angular2webpack-seed@1.0.0 build: `rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail`
26 error Exit status 2
27 error Failed at the angular2webpack-seed@1.0.0 build script 'rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular2webpack-seed package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular2webpack-seed
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular2webpack-seed
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by jorawarsingh** [comment]
this a issue with webpack [take a look]("zone.js": "~0.6.17"). If you build only by running npm webpack it will work without error.
